# Generated by Django 5.1.1 on 2024-10-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notification_advance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
