# Generated by Django 5.1.1 on 2024-10-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_location_notification_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cloud_coverage',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
